"""Initial commit

Revision ID: f0bccc0a392f
Revises: 9950f3fe6e16
Create Date: 2023-07-24 10:27:57.424284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0bccc0a392f'
down_revision = '9950f3fe6e16'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
