"""test

Revision ID: f3bc97fad19b
Revises: 6eb94d7239c0
Create Date: 2023-08-14 22:08:41.484872

"""

# revision identifiers, used by Alembic.
revision = 'f3bc97fad19b'
down_revision = '6eb94d7239c0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
